### ISSUE TITLE
Control Resource Presence via Permissions

### ISSUE THREAD

**Issue by szi** [marmelab/aor-permissions#21] opened 2017-07-20 01:36 UTC
I am trying to let Resources and their presence in the menu be controlled via permissions as shown in the code below, but it doesn't seem to work. Currently the menu item for the Resource just disappears permanently, and the authclient never even gets queried via AUTH_GET_PERMISSIONS.  If it's supposed to work, what am I doing wrong? If it's not implemented for Resources yet, I think this would be an immensely useful feature to have!

```
const App = () => (
  <AuthProvider authClient={authClient}>
  <Admin restClient={restClient}>
    <WithPermission value="can_see_secret_data">
      <Resource name="secret_data" list={SecretDataList} />
    </WithPermission>
    <Resource name="public_data" list={PublicDataList} />
  </Admin>
  </AuthProvider>
);
```

**Comment by szi** [comment] 2017-07-20 15:16
As an update I found a nice workaround. I just made my own menu by copying the admin-on-rest's Menu.js and added permissions support by wrapping the MenuItemLink with a `<WithPermission value={resource.perm}> `as so:

```
import React from 'react';
import PropTypes from 'prop-types';
import inflection from 'inflection';
import pure from 'recompose/pure';
import compose from 'recompose/compose';
import { DashboardMenuItem } from 'admin-on-rest';
import { MenuItemLink } from 'admin-on-rest';
import { translate } from 'admin-on-rest';
import { WithPermission } from 'aor-permissions';

const styles = {
    main: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        height: '100%',
    },
};

const translatedResourceName = (resource, translate) =>
    translate(`resources.${resource.name}.name`, {
        smart_count: 2,
        _: resource.options && resource.options.label ?
            translate(resource.options.label, { smart_count: 2, _: resource.options.label }) :
            inflection.humanize(inflection.pluralize(resource.name)),
    });

const MyMenu = ({ hasDashboard, onMenuTap, resources, translate, logout }) => (
    <div style={styles.main}>
        {hasDashboard && <DashboardMenuItem onTouchTap={onMenuTap} />}
        {resources
            .filter(r => r.list)
            .map(resource =>
                <WithPermission value={resource.perm}>
                <MenuItemLink
                    key={resource.name}
                    to={`/${resource.name}`}
                    primaryText={translatedResourceName(resource, translate)}
                    leftIcon={<resource.icon />}
                    onTouchTap={onMenuTap}
                />
                </WithPermission>,
            )
        }
        {logout}
    </div>
);

MyMenu.propTypes = {
    hasDashboard: PropTypes.bool,
    logout: PropTypes.element,
    onMenuTap: PropTypes.func,
    resources: PropTypes.array.isRequired,
    translate: PropTypes.func.isRequired,
};

MyMenu.defaultProps = {
    onMenuTap: () => null,
};

const enhance = compose(
    pure,
    translate,
);

export default enhance(MyMenu);
```

Using that, I can now add permission-controlled resources to my app by simply giving them a "perm" property, such as:

```
<AuthProvider authClient={authClient}>
<Admin menu={MyMenu} restClient={restClient}>
<Resource perm="can_see_secret_data" name="secret_data" list={SecretDataList} />
<Admin restClient={restClient}>
</AuthProvider>`
```

Only limitation right now is that every resource (except dashboard) needs to have a valid perm parameter, or else it won't show. Hope this workaround is useful for others who have requested similar feature...

**Comment by djhi** [comment] 2017-07-20 16:28
Nice! I'll keep this issue open until we decide whether to officially support this or to add a recipe section in the documentation

**Comment by djhi** [comment] 2017-07-24 11:19
Please see and comment https://github.com/marmelab/aor-permissions/pull/22

**Comment by djhi** [comment] 2017-08-03 11:03
Duplicate of #13 (I know, not exactly but it will be addressed at the same time)

**Closed as completed by djhi** 2017-08-03 11:03 UTC
Labels: enhancement
