### ISSUE TITLE
withPermission.js:182 Uncaught (in promise) TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by prakashjais99** [marmelab/aor-permissions#17] opened 2017-07-11 16:13 UTC
Getting below uncaught exception  when used for menu rendering
withPermission.js:182 Uncaught (in promise) TypeError: Cannot read property 'source' of undefined
Have Used authprovider for authclient
Code:

```js
const Menu = ({onMenuTap, translate, logout}) => (
    <div style={styles.main}>
        <WithPermission value="Admin">
            <DashboardMenuItem onTouchTap={onMenuTap}/> {adminItems.map(item => (

                <MenuItem
                    key={item.resource}
                    containerElement={< Link to = {
                    `/${item.resource}`
                } />}
                    primaryText={item.name}
                    leftIcon={item.icon}
                    onTouchTap={onMenuTap}/>

            ))}
        </WithPermission>
        {logout}
    </div>
);
```

**Comment by djhi** [comment] 2017-08-03 11:01
Can't reproduce the problem. Can you set up a codepen or similar ?

**Comment by djhi** [comment] 2017-08-22 11:46
No news for some time, closing it.

**Closed as completed by djhi** 2017-08-22 11:46 UTC
